baseurl = "https://grapehut.dpdns.org/me"
title = "小饅頭の部屋"
theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
#style = "monokai"
style = "github-light"

[params]
  author = "小饅頭の部屋"
  info = ""
  description = "小饅頭の部屋"
  keywords = "blog,developer,personal"
  avatarurl = "avatar.png"
  #gravatar = "test@test.com"
  faviconSVG = "favicon.svg"
  favicon_32 = "favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"

  since = 2024
  license= "<a href='https://icp.gov.moe/?keyword=20241189' target='_blank'>萌ICP备20241189号</a>"

  enableTwemoji = true
  colorScheme = "auto"  #"auto" or "light" or "dark"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css","css/APlayer.min.css"]
  customJS = ["js/sakuraPlus.js","js/typed.min.js","js/typed.js","js/APlayer.min.js","js/musicPlayer.js"]
  customRemoteJS= ["<script src='https://app.rybbit.io/api/script.js' data-site-id='1684' defer></script>","<script async src='https://www.googletagmanager.com/gtag/js?id=G-DRGNRYJ7WE'></script>","<script>window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-DRGNRYJ7WE');</script>","<script async src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9661896697976587' crossorigin='anonymous'></script>","<script src='https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js'></script>","<script src='https://cdn.jsdelivr.net/npm/jquery-ui@1.14.1/dist/jquery-ui.min.js'></script>","<script src='https://cdn.jsdelivr.net/gh/hst1189/live2d-widget/autoload.js'></script>"]
  
  manifest = ""
  mask_icon = ""
  touchicon = ""
  
  enableMusic = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"


# Social links
[[params.social]]
  name = "Line"
  icon = "fa-brands fa-line fa-2x"
  weight = 1
  url = "https://access.line.me/oauth2/v2.1/login?fromDomain=access-auto.line.me&loginState=nBeMaOY7Mdu5aFeSo1hVfn&line_auto_login_error=universal_link_error&loginChannelId=1445834080&returnUri=oauth2v2.1authorizeconsentbot_promptnormalscopeopenidprofileresponse_typecodestateRhiVgBoLDGredirect_urihttps3A2F2Fform.tonariwa.com2Fsuntory2Fmeasure_url3Fcpid3Dtennensui_sampling426lcd3D126type3D126nonceEvutxGZ894client_id1445834080"
  target = "_blank"

[[params.social]]
  name = "Wechat"
  icon = "fa-brands fa-weixin fa-2x"
  weight = 2
  url = "https://web.wechat.com/uklccp?lang=en_US&t=v2/index"
  target = "_blank"
  
[[params.social]]
  name = "Telegram"
  icon = "fa-brands fa-telegram fa-2x"
  weight = 3
  url = "https://web.telegram.org/"
  target = "_blank"

[[params.social]]
  name = "X"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 4
  url = "https://x.com/"
  target = "_blank"

[[params.social]]
  name = "Mail"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 5
  url = "mailto:call@grapehut.xyz"
  target = "_blank"





# Menu links
[menu]
[[menu.main]]
  name = "小饅頭の部落格 🐯"
  pre = "fa-solid fa-blog fa-2x"
  weight = 1
  url = "https://grapehut.dpdns.org/"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の音楽 🎸"
  pre = "fa-solid fa-headphones-simple fa-2x"
  weight = 2
  url = "https://music.gdstudio.xyz/"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の英語角 🐮"
  pre = "fa-solid fa-book fa-2x"
  weight = 3
  url = "https://grapehut.dpdns.org/NCE"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のiptv电视 📺"
  pre = "fa-brands fa-chromecast fa-2x"
  weight = 4
  url = "https://grapehut.dpdns.org/iptv-m3u"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のFC游戏机 🎮"
  pre = "fa-solid fa-gamepad fa-2x"
  weight = 5
  url = "https://rs00804457.oners.jp"
  target = "_blank"


[[menu.main]]
  name = "-"
  pre = "fa-solid fa-arrow-right fa-2x"
  weight = 10
  url = "#"
  target = "_blank"

  
[[menu.main]]
  name = "小饅頭の家庭影院 I（libretv）🤩"
  pre = "fa-solid fa-photo-film fa-2x"
  weight = 11
  url = "https://libretv-1oi.pages.dev"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の家庭影院 II（moontv）🤠"
  pre = "fa-solid fa-film fa-2x"
  weight = 12
  url = "https://moontv-ebs.pages.dev"
  target = "_blank"
  
[[menu.main]]
  name = "小饅頭のtts I（libretts）🎙️"
  pre = "fa-solid fa-microphone fa-2x"
  weight = 13
  url = "https://libretts-4l5.pages.dev"
  target = "_blank"
  
[[menu.main]]
  name = "小饅頭のtts II（tts-voice-magic）🎙️"
  pre = "fa-solid fa-microphone fa-2x"
  weight = 14
  url = "https://tts-voice-magic.hst1189.workers.dev/"
  target = "_blank"
  

[[menu.main]]
  name = "小饅頭の图床 🖼️"
  pre = "fa-solid fa-image fa-2x"
  weight = 15
  url = "https://cloudflare-imgbed-1po.pages.dev"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のAI文生图 🖼️"
  pre = "fa-solid fa-image fa-2x"
  weight = 16
  url = "https://cf-ai-image.hst1189.workers.dev"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のShortURL ♾️"
  pre = "fa-solid fa-chain fa-2x"
  weight = 17
  url = "https://short-url-2vm.pages.dev/"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の收藏夹 I 🔖"
  pre = "fa-solid fa-list fa-2x"
  weight = 18
  url = "https://web-nav.hst1189.workers.dev/"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の收藏夹 II 🔖"
  pre = "fa-solid fa-list fa-2x"
  weight = 19
  url = "https://grapehut.dpdns.org/webstack"
  target = "_blank"



  





[[menu.main]]
  name = "-"
  pre = "fa-solid fa-arrow-right fa-2x"
  weight = 20
  url = "#"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の萌娘Live2D 🐱"
  pre = "fa-solid fa-venus-mars fa-2x"
  weight = 21
  url = "https://grapehut.dpdns.org/live2d-widget"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の萌娘Live2D-Cubism3 🐶"
  pre = "fa-solid fa-venus-double fa-2x"
  weight = 22
  url = "https://grapehut.dpdns.org/live2d-cubism3"
  target = "_blank"




[[menu.main]]
  name = "--"
  pre = "fa-solid fa-arrow-right fa-2x"
  weight = 30
  url = "#"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のProduct宣伝模板 🥷"
  pre = "fa-brands fa-d-and-d fa-2x"
  weight = 31
  url = "https://abc-product-portal.pages.dev"
  target = "_blank"
  
[[menu.main]]
  name = "小饅頭の字体甄选 (hugo) 🐭"
  pre = "fa-solid fa-feather fa-2x"
  weight = 32
  url = "https://myfont.grapehut.dpdns.org/"
  target = "_blank"

[[menu.main]]
  name = "mirai-tech (hugo) 👽"
  pre = "fa-solid fa-city fa-2x"
  weight = 33
  url = "https://miraitech.grapehut.dpdns.org/"
  target = "_blank"
  
[[menu.main]]
  name = "blind-date (hugo) 💘"
  pre = "fa-solid fa-heart fa-2x"
  weight = 34
  url = "https://blinddate.grapehut.dpdns.org/"
  target = "_blank"

[[menu.main]]
  name = "rentacar-twins (hugo) 🚗"
  pre = "fa-solid fa-car fa-2x"
  weight = 35
  url = "https://rentacar-twins.grapehut.dpdns.org/"
  target = "_blank"
  
[[menu.main]]
  name = "play-with-gmeek 🚀"
  pre = "fa-solid fa-rocket fa-2x"
  weight = 36
  url = "https://gmeek.dpdns.org/"
  target = "_blank"



[[menu.main]]
  name = "---"
  pre = "fa-solid fa-arrow-right fa-2x"
  weight = 40
  url = "#"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のn8n 👺"
  pre = "fa-brands fa-hubspot fa-2x"
  weight = 41
  url = "http://192.168.0.200:5678/"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のGeminiBalance 🤖"
  pre = "fa-brands fa-google fa-2x"
  weight = 42
  url = "http://192.168.0.200:8000/"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の1Panel 🦞"
  pre = "fa-solid fa-table fa-2x"
  weight = 43
  url = "http://192.168.0.200:40729/c363029430"
  target = "_blank"

[[menu.main]]
  name = "小饅頭の网站监控 😎"
  pre = "fa-solid fa-user-secret fa-2x"
  weight = 44
  url = "https://klrbsexb.ap-northeast-1.clawcloudrun.com/status/1"
  target = "_blank"





[[menu.main]]
  name = "----"
  pre = "fa-solid fa-arrow-right fa-2x"
  weight = 50
  url = "#"
  target = "_blank"







[[menu.main]]
  name = "---------"
  pre = "fa-solid fa-arrow-right fa-2x"
  weight = 90
  url = "#"
  target = "_blank"
  

[[menu.main]]
  name = "小饅頭のVPN节点I 🥷"
  pre = "fa-brands fa-expeditedssl fa-2x"
  weight = 91
  url = "https://x10host999.pages.dev/panel"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のVPN节点II 🥷"
  pre = "fa-brands fa-expeditedssl fa-2x"
  weight = 92
  url = "https://cf996.miraitech-chiyoda.com/"
  target = "_blank"

[[menu.main]]
  name = "小饅頭のVPN节点III 🥷"
  pre = "fa-brands fa-expeditedssl fa-2x"
  weight = 93
  url = "https://hst1189-myspace.hf.space/sub"
  target = "_blank"

